package com.legally.llm;

import com.legally.model.JurisdictionContext;
import com.legally.model.LegalDocumentType;

import java.util.Locale;

public final class LegalDocumentFallback {

    private LegalDocumentFallback() {
    }

    public static String generate(LegalDocumentDraftRequest request) {
        LegalDocumentType documentType = request.documentType();
        String title = request.title();
        String facts = request.facts();
        JurisdictionContext jurisdiction = request.jurisdiction();

        if (documentType == LegalDocumentType.DEMAND_LETTER) {
            return """
                    [DATE]

                    To: [LANDLORD / COUNTERPARTY NAME]
                    From: [YOUR FULL NAME]
                    Re: FORMAL DEMAND - Tenancy / Contract Breach

                    Dear Sir/Madam,

                    I write regarding the following facts:
                    %s

                    Your conduct constitutes a breach of our agreement and applicable law. I demand that you [specify remedy: revert unlawful rent increase / cease eviction threats / remedy breach] within FOURTEEN (14) days of receipt of this letter.

                    If you fail to comply, I will pursue all available civil remedies without further notice, including court action and complaints to relevant authorities.

                    Yours faithfully,

                    [YOUR NAME]
                    [PHONE / EMAIL]

                    ---
                    Generated by Legally. Review with a licensed lawyer before execution.
                    """.formatted(facts);
        }

        return """
                %s
                Jurisdiction: %s (%s)

                [PARTY A NAME] ("Party A")
                [PARTY B NAME] ("Party B")

                BACKGROUND
                %s

                OPERATIVE TERMS
                1. [Insert key terms based on the facts above and local law.]
                2. This template was generated because no AI provider was available. Configure API keys and retry.

                GOVERNING LAW
                This agreement shall be governed by the laws of %s.

                SIGNATURES

                _________________________          _________________________
                Party A                            Party B
                Date: [DATE]                       Date: [DATE]

                ---
                Generated by Legally. Review with a licensed lawyer before execution.
                """.formatted(
                title.toUpperCase(Locale.ROOT),
                jurisdiction.displayLabel(),
                documentType.getDisplayName(),
                facts,
                jurisdiction.getCountryName());
    }
}
